from . import hr_state
from . import hr_municipality
from . import hr_employee_inherit
from . import hr_employee_course
from . import hr_thematics
from . import hr_courses
from . import hr_establecimientos
from . import hr_tematicas
from . import hr_agente
from . import hr_modalidad
from . import hr_capacitacion
from . import hr_estudios
from . import hr_probatorio
from . import hr_institucion
from . import hr_occupation
