from . import res_partner
from . import res_partner_industry
from . import res_partner_bank
from . import product_template
from . import purchase_general_requisition
from . import purchase_acquisition
from . import purchase_acquisition_line
from . import purchase_requisition_service
from . import hr_employee
from . import purchase_requisition
from . import purchase_order
from . import purchase_incoterm_location